In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.1'

## **Creating arrays**

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1, 2, 3, 5, 7, 12])

In [8]:
a

array([ 1,  2,  3,  5,  7, 12])

In [9]:
a[2]

np.int64(3)

In [10]:
a[2] = 10

In [11]:
a

array([ 1,  2, 10,  5,  7, 12])

In [14]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
range(3, 10)

range(3, 10)

In [16]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## **Multi-dimensional arrays**

In [17]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [23]:
n[0]

array([1, 2, 3])

In [24]:
n[2] = [1, 1, 1]

In [25]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [26]:
n[:, 1]

array([2, 5, 1])

In [27]:
n[:]

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [28]:
n[:, 2]

array([3, 6, 1])

In [29]:
n[:, 2] = [3, 3, 3]

In [30]:
n

array([[1, 2, 3],
       [4, 5, 3],
       [1, 1, 3]])

## **Randomly generated arrays**


In [33]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [34]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [36]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## **Element-wise operations**

In [37]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [38]:
a + 1

array([1, 2, 3, 4, 5])

In [39]:
a * 2

array([0, 2, 4, 6, 8])

In [40]:
10 + (a * 2) ** 2

array([10, 14, 26, 46, 74])

In [42]:
b = (10 + (a * 2)) ** 2 / 100

In [43]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [44]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## **Comparison operations**

In [45]:
a

array([0, 1, 2, 3, 4])

In [46]:
a >= 2

array([False, False,  True,  True,  True])

In [47]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [48]:
a > b

array([False, False,  True,  True,  True])

In [49]:
a[a > b]

array([2, 3, 4])

## **Summarizing operations**

In [51]:
a

array([0, 1, 2, 3, 4])

In [52]:
a.min()

np.int64(0)

In [53]:
a.max()

np.int64(4)

In [54]:
a.sum()

np.int64(10)

In [55]:
a.mean()

np.float64(2.0)

In [56]:
a.std()

np.float64(1.4142135623730951)

In [58]:
n

array([[1, 2, 3],
       [4, 5, 3],
       [1, 1, 3]])

In [59]:
n.sum()

np.int64(23)