In [2]:
import numpy as np

In [3]:
u = np.array([2, 4, 5, 6])

In [4]:
u

array([2, 4, 5, 6])

In [5]:
v = np.array([1, 0, 0, 2])

In [6]:
u + v

array([3, 4, 5, 8])

In [7]:
u.dot(v)

np.int64(14)

In [8]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [9]:
U.dot(v)

array([14,  5,  5])

In [11]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

In [12]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [13]:
I = np.eye(3)

In [14]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [15]:
Vs = V[[0, 1, 2]]

In [16]:
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [17]:
Vs_inv = np.linalg.inv(Vs)

In [18]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])